import React from "react";
import "./iconfont.css";

// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
    DAVID_DARK = "uay-david-dark",
}

export interface Props extends React.HTMLAttributes<HTMLSpanElement> {
    type: IconClass;
    children?: React.ReactNode;
    iconPosition?: "left" | "right";
}

export class Icon extends React.PureComponent<Props> {
    static displayName = "Icon";

    static defaultProps: Partial<Props> = {
        iconPosition: "left",
    };

    override render() {
        const { type, children, iconPosition, className, ...restProps } = this.props;
        if (children) {
            if (iconPosition === "right") {
                return (
                    <span className={`g-uay-icon-with-text-on-left ${className ? className : ""}`} {...restProps}>
                        <span>{children}</span>
                        <i className={`g-uay-icon ${type}`} />
                    </span>
                );
            } else {
                return (
                    <span className={`g-uay-icon-with-text-on-right ${className ? className : ""}`} {...restProps}>
                        <i className={`g-uay-icon ${type}`} />
                        <span>{children}</span>
                    </span>
                );
            }
        } else {
            return <i className={`g-uay-icon ${type} ${className ? className : ""}`} {...restProps} />;
        }
    }
}
