import React from "react";
import "./iconfont.css";

// Attention: This file is generated by "yarn icon", do not modify

export enum IconClass {
    AIRBNB = "demo-airbnb",
    AMEX = "demo-amex",
    ANGULAR = "demo-angular",
    APP_STORE = "demo-app-store",
    APPLE = "demo-apple",
    ASANA = "demo-asana",
    ATOM = "demo-atom",
    BACKPACK = "demo-backpack",
    BEHANCE = "demo-behance",
    BIKE = "demo-bike",
    BREAD_SLICE = "demo-bread-slice",
    BREAKFAST_BOWL = "demo-breakfast-bowl",
}

export interface Props extends React.HTMLAttributes<HTMLSpanElement> {
    type: IconClass;
    children?: React.ReactNode;
    iconPosition?: "left" | "right";
}

export class Icon extends React.PureComponent<Props> {
    static displayName = "Icon";

    static defaultProps: Partial<Props> = {
        iconPosition: "left",
    };

    override render() {
        const { type, children, iconPosition, className, ...restProps } = this.props;
        if (children) {
            if (iconPosition === "right") {
                return (
                    <span className={`g-demo-icon-with-text-on-left ${className ? className : ""}`} {...restProps}>
                        <span>{children}</span>
                        <i className={`g-demo-icon ${type}`} />
                    </span>
                );
            } else {
                return (
                    <span className={`g-demo-icon-with-text-on-right ${className ? className : ""}`} {...restProps}>
                        <i className={`g-demo-icon ${type}`} />
                        <span>{children}</span>
                    </span>
                );
            }
        } else {
            return <i className={`g-demo-icon ${type} ${className ? className : ""}`} {...restProps} />;
        }
    }
}
